### ISSUE TITLE
Update Material modules imports

### ISSUE THREAD

**Issue by christophechevalier** [wesleygrimes/angular-ngrx-chuck-norris#3]
https://github.com/ngHighCountry/angular-ngrx-chuck-norris/blob/bf9c8849eef35bb78d8b0cd6f79f9b7e074aa258/src/app/app.module.ts#L4-L9

The imports have change in Material.
Now, it's : 

```
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';
```

**Comment by wesleygrimes** [comment]
@christophechevalier can you provide me the documentation or link to where this is stated? I just want to confirm, I cannot find anything mentioning the imports have changed.

**Comment by wesleygrimes** [comment]
This should be resolved now. Thanks!
